steps:
  # Deploy to Cloud Functions (no Docker needed)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'functions'
      - 'deploy'
      - 'kayzen-campaigns-fetcher'
      - '--runtime'
      - 'python311'
      - '--trigger-http'
      - '--allow-unauthenticated'
      - '--memory'
      - '512MB'
      - '--timeout'
      - '300s'
      - '--region'
      - 'europe-west1'
      - '--source'
      - '.'
      - '--entry-point'
      - 'fetch_kayzen_campaigns'
      - '--gen2'
      - '--set-env-vars'
      - 'KAYZEN_API_KEY=${_KAYZEN_API_KEY},KAYZEN_API_SECRET=${_KAYZEN_API_SECRET},KAYZEN_USERNAME=${_KAYZEN_USERNAME},KAYZEN_PASSWORD=${_KAYZEN_PASSWORD},GCP_PROJECT_ID=$PROJECT_ID,BIGQUERY_DATASET_ID=${_BIGQUERY_DATASET_ID},BIGQUERY_TABLE_ID=${_BIGQUERY_TABLE_ID}'

# Substitution variables (set these in Cloud Build trigger)
substitutions:
  _KAYZEN_API_KEY: 'your-kayzen-api-key'
  _KAYZEN_API_SECRET: 'your-kayzen-api-secret'
  _KAYZEN_USERNAME: 'your-kayzen-username'
  _KAYZEN_PASSWORD: 'your-kayzen-password'
  _BIGQUERY_DATASET_ID: 'your-dataset-id'
  _BIGQUERY_TABLE_ID: 'your-table-id'

options:
  logging: CLOUD_LOGGING_ONLY
